version: '3.3'

services:
  app:
    build: ./fizzbuzz
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./fizzbuzz/app:/usr/src/app/
    env_file:
      - ./.env.dev
    restart: always

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fizzbuzz
    ports:
      - 5405:5432
    restart: always

volumes:
  postgres-data: