version: '3.3'

services:
  api:
    build: ./fizzbuzz # mettre docker file 
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    restart: always

  db:
    image: postgres:13-alpine
    ports:
      - 5405:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fizzbuzz
