version: '3.3'

services:
  api:
    build: ./fizzbuzz
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    restart: always
    volumes:
      - ./fizzbuzz/api:/usr/src/app/

  db:
    image: postgres:13-alpine
    ports:
      - 5405:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fizzbuzz
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Possible issue : Volumes can't be mouted with Ubuntu (known issue) so comment it
# in order to launch container
volumes:
  postgres-data: